name: first-workflow
on:
  push:
    branches: ["main"]

    workflow_dispatch:

jobs:
  sample-test:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Installing python env
        uses: actions/setup-python@v5

      - name: Running the python script
        run: python3 scripts/run.py

      - name: Confirming completion
        run: echo "Successully completed execution"

