name: first-workflow
on:
  push:
    branches: ["main"]

    workflow_dispatch:

jobs:
  sample-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python

      - name: Running the python script
        run: python3 scripts/run.py

      - name: Confirming completion
        run: echo "Successully completed execution"

