name: first-workflow
on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  sample-test:
    runs-on: self-hosted
    steps:
        
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Installing python env
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Running the python script
        run: python3 scripts/run.py

      - name: Printing Secret Message
        run: echo "The secret message is ${{ secrets.SECRET_MESSAGE}}"

      - name: Confirming completion
        run: echo "Successully completed execution"

