name: first-workflow
on:
  push:
    branches: ["main"]

    workflow_dispatch:

jobs:
  sample-test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Printing
        run: |
          echo "Hello world!"
          echo "This is running on self hosted Runner"
